apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hin-artifact
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=hin-artifact"
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - demo
    - spring
    - openapiv3
    - vmware-explore
  links:
    - url: https://spring.io
      title: Spring Framework
      type: framework
    - url: https://spec.openapis.org/oas/latest.html
      title: OpenAPI v3 Spec
      type: specification

spec:
  type: service
  lifecycle: experimental
  owner: hin-team
  system: demo-system
  providesApis:
    - api:for-developer/hin-artifact
  consumesApis:
    - api:tanzu-system/system-api-for-demo
  subcomponentOf:
    - component:another-namespace/someother
